openapi: 3.0.1
info:
  title: IT-Wallet User - IO Web v1
  description: REST APIs consumed by IO WEB application
  version: v1
servers:
- url: https://apim.internal.wallet.io.pagopa.it/api/wallet/ioweb/v1
paths:
  "/wallet-instances/current/status":
    get:
      summary: GetCurrentWalletInstanceStatus
      operationId: getCurrentWalletInstanceStatus
      parameters:
      - in: header
        name: fiscal-code
        required: true
        schema:
          $ref: "#/components/schemas/FiscalCode"
      responses:
        "200":
          description: Wallet Instance status successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletData"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
  "/wallet-instances/{id}/status":
    put:
      summary: SetWalletInstanceStatus
      operationId: setWalletInstanceStatus
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      description: |-
        Revoke the Wallet Instance associated with the authenticated user.
        If the Wallet Instance is already revoked, the operation succeed.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetWalletInstanceStatusData"
      responses:
        "204":
          description: Wallet Instance status successfully set
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
  "/whitelisted-fiscal-code/{fiscal-code}":
    get:
      summary: IsFiscalCodeWhitelisted
      operationId: isFiscalCodeWhitelisted
      parameters:
      - name: fiscal-code
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WhitelistedFiscalCodeData"
        "422":
          $ref: "#/components/responses/UnprocessableContent"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
components:
  responses:
    Forbidden:
      description: The server understands the request but refuses to authorize it
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    UnprocessableContent:
      description: Unprocessable Content
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
  schemas:
    SetWalletInstanceStatusData:
      type: object
      properties:
        status:
          type: string
          enum:
          - REVOKED
        fiscal_code:
          $ref: "#/components/schemas/FiscalCode"
      required:
      - status
      - fiscal_code
    WalletData:
      description: Describes the status of the wallet.
      type: object
      properties:
        id:
          type: string
        is_revoked:
          type: boolean
      required:
      - id
      - is_revoked
    WhitelistedFiscalCodeData:
      description: Describes if the fiscal code is whitelisted.
      type: object
      properties:
        is_whitelisted:
          type: boolean
      required:
      - is_whitelisted
    FiscalCode:
      type: string
      description: User's fiscal code.
      format: FiscalCode
      x-import: "@pagopa/ts-commons/lib/strings"
      example: SPNDNL80R13C555X
    ProblemJson:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: "A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable"
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this
            occurrence of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 500
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          format: uri
          description: An absolute URI that identifies the specific occurrence of
            the problem. It may or may not yield further information if dereferenced.
