name: PR PSN Infrastructure Release - Prod

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feat-add-terraform-workflow-plan-apply # Remove after testing
    # paths:
    #   - "infra/core/psn/hub/prod/**"
    #   - "infra/core/psn/spoke/prod/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes || steps.all.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        if: github.event_name != 'workflow_dispatch'

      - name: Found changed PSN Infra modules
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
        if: github.event_name != 'workflow_dispatch'
        id: changes
        with:
          filters: |
            hub:
              - 'infra/core/psn/hub/prod/**'
            spoke:
              - 'infra/core/psn/spoke/prod/**'

      - name: All PSN Infra modules (for manual trigger)
        if: github.event_name == 'workflow_dispatch'
        id: all
        run: |
          echo 'changes=["hub", "spoke"]' >> $GITHUB_OUTPUT

  # release_prod:
  #   needs: changes
  #   uses: pagopa/dx/.github/workflows/infra_apply.yaml@support/psn-adaptation #main - Temporary, to be removed when using specific psn environment
  #   name: Infrastructure Release
  #   secrets: inherit

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       infra: ${{ fromJSON( needs.changes.outputs.changes ) }}

  #   with:
  #     environment: prod
  #     base_path: infra/core/psn/${{ matrix.infra }}
  #     use_private_agent: true
  #     override_github_environment: infra-prod # TBD
  #     use_labels: true
  #     override_labels: psn
